### ISSUE TITLE
1.46 does not compile on cygwin missing *threadex symbols (win32 only?)

### ISSUE THREAD

**Issue by stepht** [DBD-SQLite/DBD-SQLite#7] opened 2014-12-15 22:06 UTC
Hi guys, cannot compile on latest 32-bit cygwin latest gcc
% stephan@armen (/home/stephan/.cpanm/work/1418675662.14608/DBD-SQLite-1.46) %
% cygcheck -dc | grep -i -e ^cygwin' ' -e ^gcc-core
Cygwin Package Information
cygwin                                   1.7.33-1
gcc-core                                 4.8.3-4

here are the compiler messages:
linker: [/usr/bin/g++ --shared -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -L/usr/local/lib -fstack-protector -Wl,-Bsymbolic SQLite.o dbdimp.o sqlite3.o -o blib/arch/auto/DBD/SQLite/SQLite.dll /opt/perl5201/lib/5.20.1/cygwin-thread-multi-64int/CORE/cygperl5_20_1.dll]
sqlite3.o:sqlite3.c:(.text+0x83ac): undefined reference to `_endthreadex'
sqlite3.o:sqlite3.c:(.text+0x9991): undefined reference to`_beginthreadex'
collect2: error: ld returned 1 exit status
Makefile:509: recipe for target 'blib/arch/auto/DBD/SQLite/SQLite.dll' failed
make: **\* [blib/arch/auto/DBD/SQLite/SQLite.dll] Error 1

note that 1.44 is fine
.shw-args(7584): </bin/sh>[-c][gcc -c  -I. -I/opt/perl5201/lib/site_perl/5.20.1/cygwin-thread-multi-64int/auto/DBI -DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -fwrapv -fno-strict-aliasing -pipe -fstack-protector -Wl,-Bsymbolic -DUSEIMPORTLIB -O3 -O2   -DVERSION=\"1.44\" -DXS_VERSION=\"1.44\"  "-I/opt/perl5201/lib/5.20.1/cygwin-thread-multi-64int/CORE"  -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_STAT3 -DNDEBUG=1 -DSQLITE_TEMP_STORE=2 -DHAVE_USLEEP=1 sqlite3.c]
rm -f blib/arch/auto/DBD/SQLite/SQLite.dll
ld2  --shared  -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -L/usr/local/lib -fstack-protector -Wl,-Bsymbolic SQLite.o dbdimp.o sqlite3.o  -o blib/arch/auto/DBD/SQLite/SQLite.dll    \
  /opt/perl5201/lib/5.20.1/cygwin-thread-multi-64int/CORE/cygperl5_20_1.dll    \

.linker: [/usr/bin/g++ --shared -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -L/usr/local/lib -fstack-protector -Wl,-Bsymbolic SQLite.o dbdimp.o sqlite3.o -o blib/arch/auto/DBD/SQLite/SQLite.dll /opt/perl5201/lib/5.20.1/cygwin-thread-multi-64int/CORE/cygperl5_20_1.dll]
chmod 755 blib/arch/auto/DBD/SQLite/SQLite.dll
"/cygdrive/c/xopt/opt/perl5201/bin/perl.exe" -MExtUtils::Command::MM -e 'cp_nonempty' -- SQLite.bs blib/arch/auto/DBD/SQLite/SQLite.bs 644
.shw-args(14460): </bin/sh>[-c]["/cygdrive/c/xopt/opt/perl5201/bin/perl.exe" -MExtUtils::Command::MM -e 'cp_nonempty' -- SQLite.bs blib/arch/auto/DBD/SQLite/SQLite.bs 644]

hth
--steph

**Comment by 6bb79df9** [comment] 2015-01-06 12:44
Hi steph,
  I also met this problem while trying to install DBD::SQLite on latest 32-bit Cygwin, after some troubleshooting I found the problem was caused by missing a SQLITE_OS_XXX C define(in this case SQLITE_OS_UNIX), by default the sqlite3.c will fall back to SQLITE_OS_WIN, which will pull in symbols like '_endthreadex' and '_beginthreadex' etc.

  Here's my workaround to fix this problem:

```sh
export PERL_MM_OPT="$PERL_MM_OPT CCFLAGS='-DSQLITE_OS_UNIX'"
```

  Hope it helps :)

**Comment by charsbar** [comment] 2015-01-06 14:31
Thanks for the report. Confirmed the same issue happened under cygwin64. It looks like a regression of SQLite 3.8.7. The latest DBD::SQLite 1.46 compiles successfully if bundled SQLite is downgraded to 3.8.6.

Basically, this is an issue of the upstream. ```-DSQLITE_OS_UNIX=1``` may help, but it's not a perfect solution, because you need to set SQLITE_OS_WIN to true to enable Cygwin-specific code in sqlite3.c. ```-DTHREADSAFE=0``` may also help, but it has its own issue.

Unless you definitely need a tweaked version of DBD::SQLite now, I'd rather wait until this is fixed in the upstream. It seems that SQLite 3.8.7 itself doesn't compile well under cygwin now (without tweaks). So, could you check if SQLite 3.8.7 compiles successfully under your environment or not, and if not, report it (the failure of SQLite library itself) to the upstream mailing list?

**Comment by l8gravely** [comment] 2015-02-06 19:32
I'm using Mobaxterm with cygwin and running into this exact same issue.  What's the trick with cygwin to fall back to an older version of sqlite3 so that I can get perl 5.14.2 to install DBD::SQLite properly, with out the hack shown above?

**Comment by charsbar** [comment] 2015-02-08 07:04
@l8gravely If you don't want to use the hack above and you don't need to use new perl VM support, you can safely install DBD::SQLite 1.44 (```cpan ISHIGAKI/DBD-SQLite-1.44.tar.gz``` etc) for the time being to avoid compilation issue.

A patch to disable threads under Cygwin (to fix this issue in a way) has been applied to the trunk of the upstream (see http://www.sqlite.org/src/info/2037442c582e51d85967bc911ea4a412eb4da573) and I'm supposing SQLite 3.8.9 would be out with that fix in it (in a few months). If everyone is happy with that solution, I can add a compilation flag to disable threads under Cygwin and start a release process of a new DBD::SQLite. Maybe it ends a bit earlier than the upstream release.

However, other solution was proposed by the maintainer of cyqlite (https://www.mail-archive.com/sqlite-users@sqlite.org/msg88356.html). No discussion was done about that yet, but it looks better to me. You might want to help convincing the upstream maintainers to apply it instead if you prefer.

**Comment by charsbar** [comment] 2017-08-28 19:24
Closing this issue as resolved. Thanks.

**Closed by charsbar** 2017-08-28 19:24 UTC
